PRODUCT_BENEFIT_RULES = {
    # BRIGHTENING & SPOT
    "niacinamide": ["mencerahkan kulit", "menyamarkan bekas jerawat", "memperkuat skin barrier"],
    "vitamin c": ["mencerahkan kulit", "meratakan warna kulit", "melindungi dari radikal bebas"],
    "ascorbic acid": ["mencerahkan kulit", "meratakan warna kulit"],
    "alpha arbutin": ["memudarkan flek hitam", "meratakan warna kulit"],
    "tranexamic acid": ["memudarkan bekas jerawat", "meratakan warna kulit"],
    "licorice": ["mencerahkan kulit", "menenangkan kulit"],
    "glutathione": ["mencerahkan kulit"],
    "mulberry extract": ["mencerahkan kulit", "menyamarkan flek hitam"],
    "bearberry": ["mencerahkan kulit", "memudarkan flek hitam"],
    "phenylethyl resorcinol": ["mencerahkan kulit", "memudarkan flek hitam"],
    "alpha arbutin 2%": ["memudarkan flek hitam", "meratakan warna kulit"],
    "alpha arbutin 3%": ["memudarkan flek hitam", "meratakan warna kulit"],
    "ferulic acid": ["antioksidan", "mencerahkan kulit"],
    "bright berries": ["antioksidan", "mencerahkan kulit"],
    "summer plum": ["mencerahkan kulit", "antioksidan"],
    "phenylethyl resorcinol": ["mencerahkan kulit", "memudarkan flek hitam"],
    "vitamin b3": ["mencerahkan kulit", "menyamarkan bekas jerawat"],
    "edelweiss extract": ["mencerahkan kulit", "melindungi skin barrier"],
    "crystal-white active": ["mencerahkan kulit hingga lapisan dalam"],
    "silver vine extract": ["mencerahkan kulit", "meningkatkan skin translucency"],
    "niacinamide + sakura": ["mencerahkan kulit", "memberikan efek glowing"],
    "advanced niacinamide": ["mencerahkan kulit", "melindungi dari blue light"],
    "alpha arbutin + niacinamide": ["mencerahkan kulit", "memudarkan flek hitam"],
    "vitamin b3 + licorice": ["mencerahkan kulit", "menyamarkan bekas jerawat"],
    "kojic acid": ["memudarkan flek hitam", "mencerahkan kulit"],
    "14x brightening booster": ["mencerahkan kulit secara intensif", "menyamarkan noda hitam"],
    "sweet cherry extract": ["mencerahkan kulit", "antioksidan"],
    "extract vit b3": ["mencerahkan kulit", "mengecilkan pori-pori"],
    "vitamin beads": ["menutrisi kulit", "mencerahkan kulit"],
    "silver vine": ["mencerahkan kulit", "meningkatkan skin translucency"],
    "brightening peptide": ["mencerahkan kulit", "meratakan warna kulit"],
    "4x berries bright": ["mencerahkan kulit", "antioksidan"],
    "20x brightening booster": ["mencerahkan kulit secara intensif"],
    "actiwhite™": ["mencerahkan kulit", "menghambat pembentukan melanin"],
    "oxyresveratrol": ["mencerahkan kulit dengan kuat", "antioksidan"],
    "starfish essence": ["mencerahkan kulit", "mempercepat regenerasi"],
    "bio-highlighter peptide": ["memberikan efek glowing", "menghaluskan tekstur"],
    "alpha arbutin 5%": ["mencerahkan kulit", "memudarkan flek hitam membandel"],
    "17x brightening booster": ["mencerahkan kulit secara ekstrem", "meratakan warna kulit"],
    "alpha arbutin 1%": ["mencerahkan kulit secara lembut", "menyamarkan noda hitam"],
    "kombucha": ["detoksifikasi kulit", "meningkatkan kecerahan alami"],
    "carrot": ["antioksidan", "mencerahkan kulit kusam"],
    "raspberry": ["melindungi kulit dari radikal bebas", "menjaga elastisitas"],
    "terminalia ferdinandiana": ["sumber vitamin C alami tertinggi", "mencerahkan wajah"],
    "pomegranate": ["anti-aging", "mencerahkan dan menutrisi kulit"],
    "kale": ["nutrisi superfood untuk kulit", "detoksifikasi"],
    

    #FIRMING & PLUMPING (Penyebab Wardah Plump & Firm muncul)
    "collagen peptide": ["menjaga elastisitas kulit", "membuat kulit kenyal", "firming"],
    "oat extract": ["menenangkan kulit", "menjaga kelembapan"],
    "skin-plumping peptide": ["menjaga elastisitas kulit", "membuat kulit kenyal"],

    # ACNE & OIL CONTROL
    "salicylic acid": ["mengatasi jerawat", "membersihkan pori-pori"],
    "azelaic acid": ["mengatasi jerawat", "menyamarkan bekas jerawat"],
    "tea tree": ["meredakan jerawat", "mengurangi minyak berlebih"],
    "zinc": ["mengontrol minyak"],
    "niacinamide zinc": ["mengontrol minyak", "mengatasi jerawat"],
    "benzoyl peroxide": ["membunuh bakteri penyebab jerawat", "mengurangi inflamasi"],
    "niacinamide 10%": ["mengontrol minyak", "menenangkan kulit", "menyamarkan bekas jerawat"],
    "salicylic acid 2%": ["mengatasi jerawat", "membersihkan pori-pori"],
    "zinc gluconate": ["mengontrol minyak", "mengurangi inflamasi jerawat"],
    "d-panthenol": ["menenangkan kulit", "menjaga kelembapan"],
    "witch hazel": ["meringkas pori-pori", "mengontrol minyak berlebih"],
    "zinc gluconate": ["mengontrol minyak", "mengurangi kilap"],
    "succinic acid": ["mengatasi jerawat untuk kulit sensitif", "mengontrol sebum"],
    "mild bha": ["membersihkan pori tanpa rasa kering", "eksfoliasi lembut"],
    "mineral powder": ["menyerap minyak berlebih", "memberikan efek smooth/matte"],
    "potassium azeloyl diglycinate": ["mencerahkan bekas jerawat", "mengatur produksi sebum"],
    "salix nigra bark extract": ["sumber alami salicylic acid", "anti-inflamasi jerawat"],
    "cinnamon bark extract": ["anti-bakteri penyebab jerawat", "menyeimbangkan minyak"],

    # SOOTHING & SENSITIVE
    "centella": ["menenangkan kulit", "mengurangi kemerahan"],
    "cica": ["menenangkan kulit", "mengurangi kemerahan"],
    "panthenol": ["menenangkan kulit", "menjaga kelembapan"],
    "allantoin": ["menenangkan kulit iritasi", "melembapkan"],
    "green tea": ["menenangkan kulit", "melindungi dari radikal bebas"],
    "aloe vera": ["menenangkan kulit", "menjaga kelembapan"],
    "chamomile": ["menenangkan kulit"],
    "beta glucan": ["menenangkan kulit", "menjaga kelembapan"],
    "shea butter": ["melembapkan kulit", "menenangkan kulit"],
    "jojoba oil": ["menenangkan kulit", "melembapkan kulit"],
    "mugwort": ["menenangkan kulit", "mengurangi kemerahan"],
    "madecassoside": ["menenangkan kulit", "memperbaiki skin barrier"],
    "cicapro": ["menenangkan kulit", "memperbaiki skin barrier"],
    "actosome retinol": ["menyamarkan tanda penuaan", "meratakan tekstur kulit"],
    "centella asiatica": ["menenangkan kulit", "mengurangi kemerahan", "memperbaiki skin barrier"],
    "cica complex": ["menenangkan kulit", "mengurangi kemerahan"],
    "bakuchiol": ["menyamarkan tanda penuaan", "meratakan tekstur kulit"],
    "prebiotic": ["menenangkan kulit", "menyeimbangkan mikrobioma kulit"],
    "heartleaf": ["menenangkan kemerahan", "detoksifikasi kulit"],
    "probiotics 9 complex": ["memperkuat pertahanan kulit", "menjaga ekosistem kulit"],
    "bisabolol": ["meredakan kemerahan", "anti-inflamasi"],
    "seaweed": ["detoksifikasi", "memberikan mineral pada kulit"],
    "hpr": ["retinoid generasi baru yang minim iritasi", "menyamarkan kerutan"],
    "synchrolife": ["melindungi kulit dari kelelahan akibat blue light"],
    "polygonum cuspidatum": ["antioksidan kuat", "menenangkan kulit"],
    "rosmarinus officinalis": ["anti-septik alami", "menenangkan kulit"],
    "camellia sinensis": ["antioksidan tinggi", "mengurangi produksi minyak"],

    # HYDRATION & BARRIER
    "hyaluronic acid": ["menjaga kelembapan kulit", "menghidrasi lapisan kulit"],
    "sodium hyaluronate": ["menjaga kelembapan kulit"],
    "glycerin": ["menjaga kelembapan kulit", "melembutkan kulit"],
    "ceramide": ["memperbaiki skin barrier", "mengunci kelembapan"],
    "cholesterol": ["memperbaiki skin barrier"],
    "squalane": ["menjaga kelembapan kulit", "melembutkan kulit"],
    "urea": ["menjaga kelembapan kulit"],
    "panthenol 5%": ["menjaga kelembapan kulit", "menenangkan kulit"],
    "quadruple hydration system": ["menghidrasi kulit", "menjaga kelembapan"],
    "hyaluronic": ["menjaga kelembapan kulit", "menghidrasi lapisan kulit"],  
    "squalane+": ["menjaga kelembapan kulit", "melembutkan kulit"],
    "oxybiome": ["menenangkan kulit", "menjaga keseimbangan mikrobioma kulit"],
    "moistprime tech": ["menjaga kelembapan kulit"],
    "aquaxyl": ["menghidrasi kulit", "mengunci kelembapan"],
    "quadruple hydration system": ["menghidrasi kulit", "menjaga kelembapan"],
    "triple protection+": ["melindungi kulit", "menjaga kelembapan kulit"],
    "14x hyaluron": ["menghidrasi kulit secara mendalam", "mengunci kelembapan"],
    "pentavitin": ["menjaga kelembapan hingga 72 jam", "memperbaiki skin barrier"],
    "deep water restore": ["menghidrasi kulit", "menenangkan kulit"],
    "cica complex + panthenol": ["menenangkan kemerahan", "memperbaiki skin barrier"],
    "nmf amino": ["menjaga kelembapan alami kulit", "memperkuat skin barrier"],
    "72h hydration active": ["menghidrasi kulit secara mendalam", "mengunci kelembapan"],
    "triple hydrating": ["menghidrasi berbagai lapisan kulit", "menjaga kelembapan"],
    "smart micro-foam complex": ["melembapkan kulit", "membersihkan dengan lembut", "menenangkan kulit"],
    "17x amino acid complex": ["menutrisi kulit", "menjaga elastisitas dan barrier"],
    "moisture magnet agent": ["mengunci kelembapan", "mencegah kulit dehidrasi"],
    "bio-hyaluronic acid": ["menghidrasi kulit secara intensif"],
    "rosebay willowherb": ["menenangkan kulit", "mengurangi kemerahan"],
    "multi probiome": ["menyeimbangkan mikrobioma kulit", "memperkuat barrier"],
    "stress relief agent": ["menenangkan kulit yang lelah"],
    "aqua ceramide 2%": ["memperbaiki skin barrier", "menjaga kadar air"],
    "11x ha": ["menghidrasi di berbagai lapisan kulit"],
    "pure rose water": ["menenangkan kulit", "menghidrasi dan menyegarkan wajah"],
    "real rose petal": ["memberikan kelembapan ekstra", "sebagai antioksidan alami"],
    "pga": ["mengunci kelembapan lebih kuat dari HA", "menjaga elastisitas kulit"],
    "hyacross 2%": ["membentuk lapisan pelindung kelembapan", "menghidrasi kulit lebih lama"],
    "marine collagen 5%": ["menjaga kekenyalan kulit", "menghidrasi secara intensif"],
    "vegan dna pentavitin": ["menghidrasi hingga 72 jam", "memperbaiki skin barrier"],
    "97% galactomyces ferment filtrate": ["mencerahkan", "mengecilkan pori", "meratakan tekstur"],
    "galactomyces": ["meningkatkan kecerahan kulit", "memperbaiki tekstur"],
    "ice plant extract": ["menyejukkan kulit", "memberikan hidrasi instan"],
    "betaine": ["menjaga keseimbangan air di sel kulit", "anti-iritasi"],
    "allantoin": ["mempercepat regenerasi kulit", "menenangkan iritasi"],
    "probiotics 9 complex": ["membantu menjaga keseimbangan mikrobioma kulit", "memperkuat skin barrier"],

    # ANTI AGING
    "retinol": ["menyamarkan tanda penuaan", "meratakan tekstur kulit"],
    "retinal": ["menyamarkan tanda penuaan"],
    "bakuchiol": ["menyamarkan tanda penuaan"],
    "peptide": ["menjaga elastisitas kulit"],
    "adenosine": ["menyamarkan garis halus"],
    "collagen": ["menjaga elastisitas kulit"],
    "resveratrol": ["antioksidan", "melindungi kulit dari penuaan"],
    "matrixyl 3000": ["menyamarkan garis halus", "menjaga elastisitas kulit", "meningkatkan produksi kolagen"],
    "peptide complex": ["menjaga elastisitas kulit", "mengurangi tanda penuaan"],
    "retinolsome 0.5%": ["menyamarkan tanda penuaan", "meratakan tekstur kulit"],
    "multi peptide": ["menjaga elastisitas kulit", "mengurangi kerutan"],
    "gold-peptide crystals": ["anti-aging", "meningkatkan elastisitas kulit"],
    "youth glow active": ["anti-aging", "meningkatkan kecerahan kulit"],
    "argireline™ peptide": ["menyamarkan garis halus", "efek mirip botox"],
    "mosscelltec™ no.1": ["memperkuat ketahanan kulit", "anti-aging"],
    "vegan retinalt booster": ["mempercepat regenerasi kulit", "anti-aging tanpa iritasi"],
    "biotech recombinant collagen": ["menjaga kekenyalan kulit", "firming"],
    "immortelle flower oil": ["anti-aging", "merevitalisasi kulit"],

    # EXFOLIATION & TEXTURE
    "glycolic acid": ["mengangkat sel kulit mati", "meratakan tekstur kulit"],
    "lactic acid": ["mengangkat sel kulit mati", "menjaga kelembapan kulit"],
    "mandelic acid": ["mengangkat sel kulit mati"],
    "pha": ["mengangkat sel kulit mati dengan lembut"],
    "bha": ["mengangkat sel kulit mati", "membersihkan pori-pori"],
    "aha": ["mengangkat sel kulit mati", "meratakan tekstur kulit"],
    "pha 5%": ["mengangkat sel kulit mati dengan lembut"],
    "lactic acid 10%": ["mengangkat sel kulit mati", "menjaga kelembapan kulit"],
    "mandelic acid 5%": ["mengangkat sel kulit mati"],
    "clarifying mineral": ["membersihkan pori", "menyegarkan kulit"],
    "carboactiv": ["membantu detoks kulit", "meningkatkan tekstur kulit"],

    # SUNSCREEN & PROTECTION
    "zinc oxide": ["melindungi kulit dari sinar UV", "mencegah kerusakan akibat UVA/UVB"],
    "titanium dioxide": ["melindungi kulit dari sinar UV"],
    "octinoxate": ["melindungi kulit dari sinar UV"],
    "tinosorb": ["melindungi kulit dari sinar UV"],
    "avobenzone": ["melindungi kulit dari sinar UVA", "mencegah kerusakan kulit"],
    "spf 15 pa++": ["melindungi kulit dari sinar UV"],
    "spf 30 pa+++": ["melindungi kulit dari sinar UV"],
    "spf 35 pa+++": ["melindungi kulit dari sinar UV"],
    "spf 50 pa++++": ["melindungi kulit dari sinar UV"],
    "broad spectrum protection": ["melindungi kulit dari sinar UVA & UVB"],

    # VITAMINS & EXTRACTS
    "8x essential vitamins": ["antioksidan", "menjaga kesehatan kulit"],
    "5x peptides": ["meningkatkan elastisitas kulit", "anti-aging"],
    "rose oil": ["menenangkan kulit", "menghidrasi kulit"],
    "rose water": ["menenangkan kulit", "melembapkan kulit"],
    "marigold extract": ["menenangkan kulit", "mengurangi kemerahan"],
    
    # OTHER POPULAR INGREDIENTS
    "vitamin e": ["antioksidan", "menjaga kelembapan kulit"],
    "caffeine": ["mengurangi bengkak", "menenangkan kulit"],
    "coenzyme q10": ["antioksidan", "mengurangi tanda penuaan"],
    "licorice root extract": ["mencerahkan kulit", "menenangkan kulit"],
    "green tea extract": ["menenangkan kulit", "melindungi dari radikal bebas"],
    "calendula": ["menenangkan kulit", "mengurangi kemerahan"],
    "amino ectoin": ["menjaga kelembapan kulit", "melindungi dari stres lingkungan"],
    "triple hydrating": ["menghidrasi kulit", "menjaga kelembapan"],
    "triple protection+": ["melindungi kulit", "menjaga kelembapan kulit"],
    "vitamin b3": ["mencerahkan kulit", "menyamarkan bekas jerawat"],
    "niacinamide 5%": ["mencerahkan kulit", "menyamarkan bekas jerawat", "menenangkan kulit"],
    "niacinamide 7%": ["mencerahkan kulit", "menyamarkan bekas jerawat", "menenangkan kulit"],
    "niacinamide 12%": ["mencerahkan kulit", "menyamarkan bekas jerawat", "menenangkan kulit"],
    "niacinamide 2%": ["mencerahkan kulit", "menyamarkan bekas jerawat"],
    "niacinamide 10%": ["mencerahkan kulit", "menyamarkan bekas jerawat", "menenangkan kulit"],
    "niacinamide b3": ["mencerahkan kulit", "menyamarkan bekas jerawat", "menenangkan kulit"]
}


# =====================================================
# CATEGORY BASE BENEFITS (KATEGORI PRODUK)
# =====================================================
CATEGORY_BASE_BENEFITS = {
    "facialwash": [
        "membersihkan kulit dari kotoran, minyak, dan sisa makeup",
        "menjaga kebersihan pori-pori",
        "mengontrol minyak berlebih"
    ],
    "toner": [
        "menyegarkan kulit setelah membersihkan wajah",
        "mempersiapkan kulit sebelum tahap skincare selanjutnya",
        "menjaga pH kulit"
    ],
    "serum": [
        "merawat permasalahan kulit secara lebih intensif",
        "memberikan nutrisi aktif ke dalam kulit",
        "meningkatkan kinerja skincare lainnya"
    ],
    "moisturizer": [
        "menjaga kelembapan kulit",
        "memperkuat lapisan pelindung kulit",
        "melembutkan kulit"
    ],
    "sunscreen": [
        "melindungi kulit dari paparan sinar matahari",
        "mencegah kerusakan kulit akibat sinar UV",
        "mengurangi risiko penuaan dini"
    ]
}